global using Microsoft.EntityFrameworkCore;
global using Microsoft.EntityFrameworkCore.Design;
global using Microsoft.EntityFrameworkCore.Metadata.Builders;
global using Microsoft.EntityFrameworkCore.Storage;
global using Fundo.Domain.Entities;
global using Fundo.Domain.ValueObjects;
global using Fundo.Domain.Repository;
global using System;
global using System.Collections.Generic;