version: '3.4'

services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server
    environment:
      MSSQL_SA_PASSWORD: "Your_password123"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Developer"
    user: root
    ports:
      - "1433:1433"
    volumes:
      - sqlserverdata:/var/opt/mssql
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "/opt/mssql-tools18/bin/sqlcmd -S localhost -U sa -P Your_password123 -C -Q 'SELECT 1' || exit 1"]
      interval: 10s
      retries: 10
      start_period: 10s
      timeout: 3s
  sqlserver.configurator:
    image: mcr.microsoft.com/mssql/server
    user: root
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    depends_on:
      sqlserver:
        condition: service_healthy
    command: >
      bash -c '
      /opt/mssql-tools18/bin/sqlcmd -S sqlserver -U sa -P Your_password123 -C -d master -i docker-entrypoint-initdb.d/init.sql;
      echo "All done!";
      '

  loanapi:
    build: .
    depends_on:
      - sqlserver
    ports:
      - "5050:8080"
    environment:
      ConnectionStrings__DefaultConnection: "Server=sqlserver;Database=LoanDB;User Id=sa;Password=Your_password123;TrustServerCertificate=true"
    restart: always

volumes:
  sqlserverdata: